language: python
python:
  - "3.6"

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+*$/

install:
  - pip3 install -e .[dev]

script:
  # As long as Travis CI uses old LTS versions with Linux kernels
  # which don't support the namespace-related ioctl's, we need to
  # skip our tests.
  #- coverage run -m unittest discover
  #- coverage report
  - (cd doc && make html)

deploy:
  - provider: pages
    skip_cleanup: true
    keep-history: true
    github-token:
      secure: "DNVAKHiLSyMTmRNi9SFY3hdYvgwjGe0bTP495CSZwV+2RSKWnMrsQawl7MKB+ZJTFBKcwX9/Bnlk6teIMpsQjfiDbEN9GfTfG/1d9cxVeFdUg85rZYxor9weeqb3gXjfkVYprZuFXEaKwwrMVzcRTh21TVpO3Mq2Fzv4MsVHkpacMi2LqDpLIw2jiob/hAu5VoYk9BcHe/5ysdLfJ2WAC+6gpq3eiDej8U3OfSlFYNvFKlG7wqfjPNg4w6cJy5OkfKA2tvVdevx1pBqzCJMu+BlqyKCgobgi3iw8Dp0OLlDCRkMwgHG/MWtHJ7T82K6MS4ExPVIAy3LJ0ySTh9F0zJbIv38TI9LuREpjUMqCQumN/mZewWkZQYxWF0FGfyS8hi6RjbDTmb6LUY9xdl4kzpHvF9+pfRAz0xY9+H9ihs6poXIPjkvB4bWRNaMQ6AvcRQzQ0QZYcEBuDqQGqFqSRBXXXv4ummCmeB+G8kt0oivOcFXG3WxaQLbXbzELMmub2Cf2dSTlC/3t7C7SWe9T7xu0nd9kl9PfUFlxEBMRyP8jryhNYpaDJBS3rCw+PxbK8j4IEu3pxKOzHpqPGUKG+WPYU/96mlfUcekE911PfHKHW37D5cluOmEby0+AxPJtw72oxiBqCAWsFOqwR+1TDk/qiqyFgYB6P9QXNYZn0GY="
      on:
      repo: $TRAVIS_REPO_SLUG
      tags: true
      branch: master
    local-dir: doc/build/html

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: "thediveo"
    password:
      secure: "X+mVHPNYCorFqQCJtJooN1p3mRrQkcuD3lhEyWTg63S/ZE7zeECWeDVBFGV6WN56uhilvYow/gUHNSEjn/pk0//WU5FvWQnL1J0GENwTXycbKrtk9BEcLoLODAxRicHvQhwl/wrTfV02IRSvtAXz/jpO5WCDkBvPnKiEShMzFiSWFTdKw89Z18LhD7mXoqB3FG3QcB2Q+KaFuXc46RL0A8jbPliRtveS2PoNemEh+CY5ZxbF7U4ALn5yS9RfNnE9sz0EZGD3nfGCKINA72CVKJrgVySncnOZJuyYc2zqugKQZDrfl2aJ5bIVlMB40LOTXrtN5bbqs42bxPasC6KqodNCLn+8SSoMjeoipeq4U7YVE0lZIQgeYBSzXDkeMyYkqXBlIR5JGUq5BY7DdHGjFdGgzVm6J0BwdXVnhYWD5uKYLTnGE67u+TFPGMWXoSbZ8y3QSgJJ2E5LbP4Vz6tdvpYtIrAp6wdNJv8HnfZ82ND2kD53H2YAIwx8JfRseVXehpZyfVsplfjABYLSTayiMCrIhOwvJu1K/iQVkvpt6qwrDpUl7SqomrCTVv4MaRDEEhqfr0ZjKsZYpIaeyMFBJ01otMxXxTtJwjJa5tpNQrTdR5zh1LEL+rN2CMlfxfc9niuxQ4P3k+Z/dv1xsEDSQTwzN7mPoC9ndPWHn6Q/H60="
    on:
      tags: true
